# Generated by Django 4.0.4 on 2022-05-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw21', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
