# Generated by Django 4.0.4 on 2022-06-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw21', '0003_group_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('address', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='cw21.group'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='cw21.contactinfo'),
        ),
    ]
